Cleanup ETT C4 models
Energinet-DataHub/opengeh-arch-diagrams pull request #74
Opened 2024-10-22 11:49 UTC by tnickelsen

2024-10-22 12:51 UTC, Sondergaard requested changes
We must change the identifier or delete the block entirely if it's not to be used.

2024-10-22 12:51 UTC, Sondergaard commented on docs/diagrams/c4-model/dh-base-model.dsl
> +        group "Microsoft" {
Why is this group added? It's not being referenced in the changes? The identifier `github` is already used, and is the reason why the pipeline is unable to build.

2024-10-22 12:57 UTC, tnickelsen commented on docs/diagrams/c4-model/dh-base-model.dsl
> +        group "Microsoft" {
Name has been corrected - I need it to make a ref to Azure AD B2C

2024-10-23 07:34 UTC, Sondergaard commented on docs/diagrams/c4-model/dh-base-model.dsl
> +        ettDkThirdPartySystem -> ett "Integrates with platform on behalf of users" "https"
If you change these lines the diagram will render.

```suggestion
        ettDkUser -> ettDk "Reads/manages granular certificates" "browser"
        ettDkThirdPartySystem -> ettDk "Integrates with platform on behalf of users" "https"
```

2024-10-23 08:09 UTC, Sondergaard approved these changes

2024-10-23 08:38 UTC, merged